esphome:
  name: aubess-ir
  friendly_name: Aubess_IR

bk72xx:
  board: generic-bk7231n-qfn32-tuya

web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "dh+FfVrorx8A1K4iU1v6efwjgRih7nJVxCXVOhCPJdQ="

ota:
  platform: esphome
  password: "3a8871bb27afb1977605c2ff55319b39"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.30.39

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aubess-Ir Fallback Hotspot"
    password: "6z8TonINQLOX"

#captive_portal:




# Example configuration entry
remote_transmitter:
  pin: P7 
  carrier_duty_percent: 50%


remote_receiver:
  pin: 
    number: P8 
    inverted: true
    mode:
      input: true
      pullup: true  
  dump: all
  

#climate:
#  - platform: coolix       # adjust to match your AC unit!
#    name: "Living Room AC"

#binary_sensor:
#  - platform: remote_receiver
#    name: "LED ON"
#    nec:
#      address: 0xFF00
#      command: 0xBA45

  
#  - platform: remote_receiver
#    name: "LED OFF"
#    nec:
#      address: 0xFF00
#      command: 0xB847

button:
  - platform: template
    name: LED-Strip On
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFF00
          command: 0xBA45
          repeat: 1
  - platform: template
    name: LED-Strip Off
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFF00
          command: 0xB847
          repeat: 1


# LED
switch:
  - platform: gpio
    name: LED
    pin: P24 
    inverted: True  
  - platform: template
    name: Led-Strip
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFF00
          command: 0xBA45
          repeat: 1
    turn_off_action: 
      - remote_transmitter.transmit_nec:
          address: 0xFF00
          command: 0xB847
          repeat: 1
      
        