esphome:
  name: esp32-s2-ledstring
  friendly_name: esp32-s2-ledstring

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "UFWffrB22y/DhCozHSjvwnO6k07C8mMFoV5NDesqBS4="

ota:
  - platform: esphome
    password: "4296f48de3d5f9e184c09c5ad7b6de92"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-S2-Ledstring"
    password: "4lUew0X1mN4d"

captive_portal:

web_server: 
  port: 80


light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO16
    num_leds: 64
    chipset: ws2812
    name: "My Light"
    id: led_matrix_light

display:
  - platform: addressable_light
    id: led_matrix_display
    addressable_light_id: led_matrix_light
    width: 8
    height: 8
    rotation: 180°
    update_interval: 16ms
    lambda: |-
          // Draw a bulls-eye pattern
          Color red = Color(0xFF0000);
          Color green = Color(0x00FF00);
          Color blue = Color(0x0000FF);
          it.rectangle(0, 0, 8, 8, red);
          it.rectangle(1, 1, 6, 6, green);
          it.rectangle(2, 2, 4, 4, blue);
          it.rectangle(3, 3, 2, 2, red);