esphome:
  name: esp32_bme680_3
  platformio_options:
    board_build.f_cpu: 80000000L

esp32:
  board: featheresp32

#  framework:
#    type: esp-idf
#    version: recommended
#    # Custom sdkconfig options
#    sdkconfig_options:
#      COMPILER_OPTIMIZATION_SIZE: y
#    # Advanced tweaking options
#    advanced:
#      ignore_efuse_mac_crc: false


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: high
  use_address: 	192.168.30.85


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Bme680 2 Fallback Hotspot"
    password: "gRYvBmC4Bmog"

captive_portal:

#external_components:
#  - source: github://sermayoral/esphome@pm1006
#    components: [ pm1006 ]
    
uart:
  rx_pin: 27
  baud_rate: 9600

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  password: "G24mqttATopenhab"

ota:
  - platform: esphome
    password: "G24mqttATopenhab"

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: BME/status
    payload: online
  will_message:
    topic: BME/status
    payload: offline


i2c:
  sda: 26
  scl: 25
  scan: True
  #id: bus_a

bme680_bsec:
    # i2c address override (default is 0x76)
    address: 0x77

    # Temperature offset if device is in enclosure and reads too high (default is 0)
    #temperature_offset: 0.9

    # Mode for IAQ sensors if device is mobile (default is static)
    #iaq_mode: mobile

    # Interval at which to save BSEC state (default is 6 hours)
    state_save_interval: 4h

sensor:
  - platform: bme680_bsec
    temperature:
      name: "BME680 Temperature"
      id: temperature
      filters:
       - delta: 0.2
       - throttle: 30s
    pressure:
      name: "BME680 Pressure"
      
      filters:
       - delta: 0.2
       - throttle: 30s
    humidity:
      name: "BME680 Humidity"
      id: humidity
      filters:
       - delta: 0.2
       - throttle: 30s

    gas_resistance:
      name: "BME680 Gas Resistance"
      filters:
       - delta: 500.0
       - throttle: 30s
    iaq:
      name: "BME680 IAQ"
      id: iaq
      filters:
        - delta: 1.0
        - throttle: 30s
#        - median

    co2_equivalent:
      name: "BME680 CO2 Equivalent"
      id: co2_equivalent
      filters:
       - delta: 1.0
       - throttle: 30s

    breath_voc_equivalent:
      name: "BME680 Breath VOC Equivalent"
      id: breath_voc_equivalent
      filters:
       - delta: 0.1
       - throttle: 30s

  - platform: pm1006
    pm_2_5:
      name: "PM2.5 Level"
      id: pm_2_5
      filters:
       - delta: 1.0
       - throttle: 30s

  - platform: internal_temperature
    name: "Internal Temperature"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO35
      inverted: true
    id: tdisplay_button_input_1
    name: "Input 1"
#    on_click:
#      then:
#        - homeassistant.service:
#            service: switch.toggle
#            data:
#              entity_id: switch.tasmota

  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    id: tdisplay_button_input_0
    name: "Input 0"
#    on_click:
#      then:
#        - homeassistant.service:
#            service: switch.toggle
#            data:
#              entity_id: switch.termo

  - platform: status
    name: "Node Status"
    id: system_status              

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "BME680 IAQ Accuracy"


button:
  - platform: restart
    name: "Restart"


color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_gray
    red: 50%
    green: 50%
    blue: 50%

font:
  - file: "fonts/Helvetica.ttf"
    id: helvetica_48
    size: 48
  - file: "fonts/Helvetica.ttf"
    id: helvetica_24
    size: 24
  - file: "fonts/Helvetica.ttf"
    id: helvetica_18
    size: 18
  - file: "fonts/Helvetica.ttf"
    id: helvetica_header
    size: 15

  - file: "fonts/Helvetica.ttf"
    id: helvetica_base
    size: 13



spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    model: TTGO TDisplay 135x240
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 90
    lambda: |-
      it.printf(64, 0, id(helvetica_header), my_red, TextAlign::TOP_CENTER,  "esp32_bme680_3");

      if (id(temperature).has_state()) {
        it.printf(0, 30, id(helvetica_base), TextAlign::BASELINE_LEFT , "Temperatur");
        it.printf(127, 30, id(helvetica_base), TextAlign::BASELINE_RIGHT , "%.1f°", id(temperature).state);
      }

      if (id(humidity).has_state()) {
        it.printf(0, 48, id(helvetica_base), TextAlign::BASELINE_LEFT , "Feuchte");
        it.printf(127, 48, id(helvetica_base), TextAlign::BASELINE_RIGHT , "%.1f%%", id(humidity).state);
      }


      if (id(pm_2_5).has_state()) {
        it.printf(0, 66, id(helvetica_base), TextAlign::BASELINE_LEFT , "PM 2.5");
        it.printf(127, 66, id(helvetica_base), TextAlign::BASELINE_RIGHT , "%.1f ug/m3", id(pm_2_5).state);
      }


      if (id(breath_voc_equivalent).has_state()) {
        it.printf(0, 82, id(helvetica_base), TextAlign::BASELINE_LEFT , "VOC");
        it.printf(127, 82, id(helvetica_base), TextAlign::BASELINE_RIGHT , "%0.1f ppm", id(breath_voc_equivalent).state);
      }

      if (id(co2_equivalent).has_state()) {
        it.printf(0, 100, id(helvetica_base), TextAlign::BASELINE_LEFT , "co2");
        it.printf(127, 100, id(helvetica_base), TextAlign::BASELINE_RIGHT , "%0.1f ppm", id(co2_equivalent).state);
      }

      if (id(iaq).has_state()) {
        it.printf(0, 118, id(helvetica_base), TextAlign::BASELINE_LEFT , "IAQ");
        it.printf(127, 118, id(helvetica_base), TextAlign::BASELINE_RIGHT , "%0.0f", id(iaq).state);
      }




