esphome:
  name: esp32-pasco2
  friendly_name: esp32_pasco2

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "tyvvNzyD7Vf6RI7Phq2wyXy0Gm3fXE83IjzEsQvD6yQ="

ota:
  platform: esphome
  password: "57b96903b20d600326af53d43b5a11b5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Pasco2 Fallback Hotspot"
    password: "ngdIqx0eJsGc"

captive_portal:

external_components:
  - source: github://circuitvalley/esphome
    components: ["pasco2"]


i2c:
  sda: GPIO17
  scl: GPIO18
  # There is some problems with i2c scan so turn scan off if problem appear on your board
  scan: false
  id: bus_a

sensor:
  - platform: pasco2
    co2:
      name: "PASCO2 CO2"
    measurement_mode: periodic
    update_interval: 5s
  
  - platform: dps310
    temperature:
      name: "Outside Temperature"
    pressure:
      name: "Outside Pressure"
    address: 0x77
    update_interval: 60s