esphome:
  name: coffeemaker-lnz-b01-2
  on_boot:
    priority: 600
    then:
      - lambda: |-
          if (digitalRead(39) == HIGH) {
            ESP_LOGI("wakeup", "Wakeup durch Taste erkannt, sende MQTT!");
            id(my_mqtt_publish_on_wakeup) = true;
          }

globals:
  - id: my_mqtt_publish_on_wakeup
    type: bool
    restore_value: no
    initial_value: 'false'
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password

  on_connect:
    then:
      - lambda: |-
          if (id(my_mqtt_publish_on_wakeup)) {
            ESP_LOGI("mqtt", "Wakeup MQTT wird gesendet!");
            id(my_mqtt_publish_on_wakeup) = false;
            ESPHomeMQTTClient::get()->publish("coffeemaker_lnz_b01_2/sensor/wakeup_report/state", "WAKEUP");
          }
# LilyGO T5_V2.3_2.13




esp32:
  board: esp32dev
  framework:
    type: esp-idf


# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: high
  


captive_portal:



# Home Assistant
api:

ota:
  - platform: esphome
    password: "G24mqttATopenhab"
    

web_server:
  port: 80



binary_sensor:
#  - platform: gpio
#    pin:
#        number: 39
#        inverted: true
#    name: "Report broken Coffee Machine"
#    filters:
#    - delayed_off: 10ms

  - platform: gpio
    pin:
        number: 36
        inverted: true
    name: "Report working Coffee Machine"
    filters:
    - delayed_off: 10ms
    on_press:
      then:
        - mqtt.publish:
            topic: coffeemaker_lnz_b01_2/sensor/repair_report/state
            payload: "OK"
        - component.update: epaper



sensor:
  - platform: mqtt_subscribe
    name: "Coffee Machine State"
    id: coffeemaker_error_report
    topic: coffeemaker_lnz_b01_2/sensor/error_report/state  
    on_value:
        then:
          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Coffee Machine Repair State"
    id: coffeemaker_repair_report
    topic: coffeemaker_lnz_b01_2/sensor/repair_report/state
    on_value:
        then:
          - component.update: epaper




spi:
    clk_pin: 18
    mosi_pin: 23

font:
  - file: "fonts/Helvetica.ttf"
    id: arial
    size: 16
  - file: "fonts/Helvetica.ttf"
    id: helvetica_48
    size: 48
  - file: "fonts/Helvetica.ttf"
    id: helvetica_24
    size: 24
  - file: "fonts/Helvetica.ttf"
    id: helvetica_18
    size: 18
  - file: "fonts/Helvetica.ttf"
    id: helvetica_header
    size: 15

  - file: "fonts/Helvetica.ttf"
    id: helvetica_base
    size: 13

display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4
    reset_pin: 16
    model: 2.13in-ttgo-b73
    rotation: 90
    full_update_every: 100
    update_interval: never
    lambda: |-
        int y = 8;
        int const y_inc = 16;
        // Icon und Text für Fehlerzustand
        if (id(coffeemaker_error_report).state == "Problem") {
          it.print(0, y, id(helvetica_24), "\u26A0"); // Warn-Icon
          it.printf(30, y, id(arial), "Problem mit Kaffeemaschine!");
        } else {
          it.print(0, y, id(helvetica_24), "\u2714"); // OK-Icon
          it.printf(30, y, id(arial), "Kaffeemaschine OK");
        }
        y += y_inc + 8;
        // Hinweistext zu Tasten
        it.printf(0, y, id(helvetica_base), "Links: Problem melden"); y += y_inc;
        it.printf(0, y, id(helvetica_base), "Rechts: Funktion OK melden");


# deep_sleep:
#   run_duration: 10s
#   sleep_duration: 5min
#   wakeup_pin: 39
#   wakeup_pin_mode: IGNORE
#   id: my_deep_sleep

