esphome:
  name: esp32_probreeze


esp32:
  board: featheresp32
  framework:
    type: arduino
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: high


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Probreeze Hotspot"
    password: "gRYvBmC4Bmog"

captive_portal:

#external_components:
#  - source: github://sermayoral/esphome@pm1006
#    components: [ pm1006 ]
    

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  password: "G24mqttATopenhab"

ota:
  - platform: esphome
    password: "G24mqttATopenhab"

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: BME/status
    payload: online
  will_message:
    topic: BME/status
    payload: offline


i2c:
  sda: 21
  scl: 22
  scan: True
  #id: bus_a


sensor:



binary_sensor:


switch:
  - platform: gpio
    pin: 25
    name: "Dehumidifier Powerswitch"
    id: powerswitch
    inverted: true
    on_turn_on:
      - delay: 100 ms
      - switch.turn_off: powerswitch


#https://github.com/JAAlperin/esphome-adafruit-7-segment-LED-backpack-example
#https://github.com/ssieb/custom_components/tree/master/ht16k33_alpha