# LilyGO TTGO T5 V3 4.7 inch


esphome:
  name: esp32-t5-47
  

esp32:
  board: esp32dev
  framework: 
    type: arduino
    

external_components:
#  - source: github://grapefrukt/esphome-components
  - source: github://fialaste/esphome-components
    components: ["t547"]

#  - source: github://rh1rich/esphome-epd47
#    components: ["epd47"]
#  - source:
#      type: git
#      url: https://github.com/vbaksa/esphome
#      ref: dev
#    components: [lilygo_t5_47_display]


# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: high
#  use_address: 192.168.40.218


captive_portal:



# Home Assistant
api:


ota:
  - platform: esphome
    password: "528af3d2b037453d0a1839ae656fa71c"

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password


button:
  - platform: restart
    name: "${esp_name} Restart"

  - platform: template
    name: "${esp_name} Refresh"
    icon: "mdi:update"
    on_press:
      then:
      - component.update: t5_display

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO39
      inverted: true
    name: "${esp_name} Button 1"
    on_press:
      then:
        - component.update: t5_display
      
  - platform: gpio
    pin: 
      number: GPIO34
      inverted: true
    name: "${esp_name} Button 2"

  - platform: gpio
    pin: 
      number: GPIO35
      inverted: true
    name: "${esp_name} Button 3"



sensor:
  - platform: mqtt_subscribe
    name: "lr_temp"
    id: lr_temp
    topic: esp_bme680_1/sensor/bme680_temperature/state  
    on_value:
        then:
          - component.update: t5_display

  - platform: mqtt_subscribe
    name: "termostat_temp"
    id: termostat_temp
    topic: esp_bme680_2/sensor/bme680_temperature/state
    on_value:
        then:
          - component.update: t5_display
    
  - platform: mqtt_subscribe
    name: "lrh_temp"
    id: lrh_temp
    topic: esp_bme680_3/sensor/bme680_temperature/state 
    on_value:
        then:
          - component.update: t5_display

  - platform: mqtt_subscribe
    name: "toilet_temp"
    id: toilet_temp
    topic: esp_bme680_4/sensor/bme680_temperature/state   
    on_value:
        then:
          - component.update: t5_display

  - platform: mqtt_subscribe
    name: "sr_temp"
    id: sr_temp
    topic: esp_bme680_5/sensor/bme680_temperature/state
    on_value:
        then:
          - component.update: t5_display

  - platform: mqtt_subscribe
    name: "srh_temp"
    id: srh_temp
    topic: esp_bme680_6/sensor/bme680_temperature/state 
    on_value:
        then:
          - component.update: t5_display

  - platform: mqtt_subscribe
    name: "outdoor_temp"
    id: outdoor_temp
    topic: esp_bme680_7/sensor/bme680_temperature/state 
    on_value:
        then:
          - component.update: t5_display

  - platform: mqtt_subscribe
    name: "lr_humi"
    id: lr_humi
    topic: esp_bme680_1/sensor/bme680_humidity/state
    on_value:
        then:
          - component.update: t5_display
    
  - platform: mqtt_subscribe
    name: "termostat_humi"
    id: termostat_humi
    topic: esp_bme680_2/sensor/bme680_humidity/state
    on_value:
        then:
          - component.update: t5_display
    
  - platform: mqtt_subscribe
    name: "srh_humi"
    id: srh_humi
    topic: esp_bme680_3/sensor/bme680_humidity/state
    on_value:
        then:
          - component.update: t5_display

  - platform: mqtt_subscribe
    name: "outdoor_humi"
    id: outdoor_humi
    topic: esp_bme680_4/sensor/bme680_humidity/state
    on_value:
        then:
          - component.update: t5_display

  - platform: mqtt_subscribe
    name: "sr_humi"
    id: sr_humi
    topic: esp_bme680_5/sensor/bme680_humidity/state 
    on_value:
        then:
          - component.update: t5_display
          
  - platform: mqtt_subscribe
    name: "lrh_humi"
    id: lrh_humi
    topic: esp_bme680_6/sensor/bme680_humidity/state
    on_value:
        then:
          - component.update: t5_display
          
  - platform: mqtt_subscribe
    name: "toilet_humi"
    id: toilet_humi
    topic: esp_bme680_7/sensor/bme680_humidity/state
    on_value:
        then:
          - component.update: t5_display






font:
  - file: "fonts/Helvetica.ttf"
    id: arial
    size: 24
  - file: "fonts/Helvetica.ttf"
    id: helvetica_48
    size: 48
  - file: "fonts/Helvetica.ttf"
    id: helvetica_24
    size: 24
  - file: "fonts/Helvetica.ttf"
    id: helvetica_18
    size: 18
  - file: "fonts/Helvetica.ttf"
    id: helvetica_header
    size: 15

  - file: "fonts/Helvetica.ttf"
    id: helvetica_base
    size: 13

display:
  - platform: t547
#  - platform: lilygo_t5_47_display
#  - platform: epd47
    id: t5_display
    rotation: 270
    update_interval: never
    lambda: |-
        int y = 8;
        int const y_inc = 32;
        it.printf(0, y, id(arial), "Wohnzimmer %.1f°C %.1f%%", id(lr_temp).get_state(), id(lr_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Thermostat %.1f°C %.1f%%", id(termostat_temp).get_state(), id(termostat_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Heizkoerper %.1f°C %.1f%%", id(lrh_temp).get_state(), id(lrh_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Klo %.1f°C %.1f%%", id(toilet_temp).get_state(), id(toilet_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Schlafzimmer %.1f°C %.1f%%", id(sr_temp).get_state(), id(sr_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Heizkoerper %.1f°C %.1f%%", id(srh_temp).get_state(), id(srh_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Aussen %.1f°C %.1f%%", id(outdoor_temp).get_state(), id(outdoor_humi).get_state()); y += y_inc;

