# https://github.com/01Space/ESP32-C3-0.42LCD

# https://circuitpython.org/board/01space_lcd042_esp32c3/
# https://community.platformio.org/t/platformio-configuration-for-esp32-c3-0-42oled-board/29103


esphome:
  name: esp32-c3-042lcd-demo
  friendly_name: ESP32-C3-0.42LCD-demo

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "A4qr6GwCH/N7VHG5BH9IhI4gdnYZbFOg4xH7D5fvRP0="

ota:
  platform: esphome
  password: "8f38aa2993a7abbcda95af66a4117104"


mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-C3-042Lcd-Demo"
    password: "I3Tqhd38KH5z"

web_server:
  port: 80

captive_portal:

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO2
    num_leds: 1
    name: "RGB Light GPIO2"
    effects:
        # Use default parameters:
        - random:
        # Customize parameters
        - random:
            name: "My Slow Random Effect"
            transition_length: 30s
            update_interval: 30s
        - random:
            name: "My Fast Random Effect"
            transition_length: 4s
            update_interval: 5s  



i2c:
  sda: GPIO5
  scl: GPIO6


font:
  - file: "fonts/helvetica.ttf"
    id: helvetica_48
    size: 48
  - file: "fonts/helvetica.ttf"
    id: helvetica_24
    size: 24
  - file: "fonts/helvetica.ttf"
    id: helvetica_18
    size: 18
  - file: "fonts/helvetica.ttf"
    id: helvetica_header
    size: 15

  - file: "fonts/helvetica.ttf"
    id: helvetica_base
    size: 13
  - file: "fonts/Roboto-Regular.ttf"
    id: roboto
    size: 26
  - file: "fonts/Roboto-Regular.ttf"
    id: roboto_small
    size: 15
  - file: "fonts/Roboto-Regular.ttf"
    id: roboto_xx_small
    size: 10

  - file: "gfonts://Roboto"
    id: roboto30
    size: 30


      # https://pictogrammers.github.io/@mdi/font/5.3.45/
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_icons
    size: 160
    glyphs:
      - "\U000F0594" # clear-night
      - "\U000F0590" # cloudy
      - "\U000F0595" # partlycloudy
      - "\U000F0591" # fog      
      - "\U000F0592" # hail
      - "\U000F0593" # lightning
      - "\U000F067E" # lightning-rainy
      - "\U000F0596" # pouring
      - "\U000F0597" # rainy
      - "\U000F0F36" # snowy
      - "\U000F067F" # snowy-rainy
      - "\U000F0599" # sunny
      - "\U000F059D" # windy
      - "\U000F059E" # windy-variant
      - "\U000F0F38" # exceptional
      
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_icons_small
    size: 56
    glyphs:
      - "\U000F10C2" # Temperature High
      - "\U000F10C3" # Temperature Low
      - "\U000F07E4" # CO2
      - "\U000F054B" # umbrella      
      - "\U000F0592" # hail
      - "\U000F0593" # lightning
      - "\U000F067E" # lightning-rainy
      - "\U000F0597" # rainy
      - "\U000F0F36" # snowy
      - "\U000F0594" # clear-night
      - "\U000F0599" # sunny
      - "\U000F07CA" # fuel
      - "\U000F024A" # flower
      - "\U000F051F" # time-remaining
      - "\U000F140B" # Energy
      - "\U000F0A72" # solar power
      - "\U000F0D9B" # solar-panel
      - "\U000F0F9B" # mdi-home-export-outline
      - "\U000F0F9C" # mdi-home-import-outline

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_icons_x_small
    size: 20
    glyphs:
      - "\U000F10C2" # Temperature High
      - "\U000F10C3" # Temperature Low
      - "\U000F07E4" # CO2
      - "\U000F054B" # umbrella      
      - "\U000F0592" # hail
      - "\U000F0593" # lightning
      - "\U000F067E" # lightning-rainy
      - "\U000F0597" # rainy
      - "\U000F0F36" # snowy
      - "\U000F0594" # clear-night
      - "\U000F0599" # sunny
      - "\U000F07CA" # fuel
      - "\U000F024A" # flower
      - "\U000F051F" # time-remaining
      - "\U000F140B" # Energy
      - "\U000F0A72" # solar power
      - "\U000F0D9B" # solar-panel
      - "\U000F0F9B" # mdi-home-export-outline
      - "\U000F0F9C" # mdi-home-import-outline


display:
  - platform: ssd1306_i2c
    model: "SSD1306 72x40"
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(roboto_xx_small), "Hello World!");
      it.printf(0, 12, id(font_icons_x_small), "\U000F054B");    