esphome:
  name: esp32s3-ttgo-d-2
  friendly_name: esp32s3-ttgo-d-2

esp32:
  variant: esp32s3
  framework:
    type: esp-idf
  flash_size: 16MB

psram:
  speed: 80MHz
  mode: octal

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Ttgo-Display"
    password: "gRYvBmC4Bmog"



#external_components:
#  - source: github://sermayoral/esphome@pm1006
#    components: [ pm1006 ]

#external_components:
#  - source: github://landonr/lilygo-tdisplays3-esphome
#    components: [tdisplays3]



# Enable logging
logger:

# Enable Home Assistant API
#api:
#  password: "G24mqttATopenhab"

ota:
  platform: esphome
  password: "gRYvBmC4Bmog"

#web_server:
#  port: 80

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      inverted: true
    id: tdisplay_button_input_1
    name: "Input 1"
#    on_click:
#      then:
#        - homeassistant.service:
#            service: switch.toggle
#            data:
#              entity_id: switch.tasmota

  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    id: tdisplay_button_input_0
    name: "Input 0"
#    on_click:
#      then:
#        - homeassistant.service:
#            service: switch.toggle
#            data:
#              entity_id: switch.termo

  - platform: status
    name: "Node Status"
    id: system_status              


sensor:
  # Wert1
  - platform: mqtt_subscribe
    name: "Netz"
    id: netz
    topic: pv/sensor/netz/state 
    on_value:
        then:
 #         - component.update: epaper
  # Wert2
  - platform: mqtt_subscribe
    name: "PV1"
    id: pv1
    topic: pv/sensor/pv1/state
    on_value:
        then:
 #         - component.update: epaper
  # Wert3  
  - platform: mqtt_subscribe
    name: "PV2"
    id: pv2
    topic: pv/sensor/pv2/state 
    on_value:
        then:
 #         - component.update: epaper
  # Wert4
  - platform: mqtt_subscribe
    name: "Eigen"
    id: eigen
    topic: pv/sensor/eigenverbrauch/state   
    on_value:
        then:
          #- component.update: epaper
  # Akt IP Adr
# Example configuration entry
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      id: ip_address


button:
  - platform: restart
    name: "Restart"

#switch:
#  - platform: gpio
#    pin: GPIO38
#    name: "Backlight"
#    id: backlight
#    internal: true
#    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: ledc
    frequency: 2000
    pin: GPIO38
    id: backlight_output

light:
  - platform: monochromatic
    output: backlight_output
    name: LCD Backlight
    id: led
    restore_mode: ALWAYS_ON
    default_transition_length: 0s


color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_gray
    red: 50%
    green: 50%
    blue: 50%

font:
  - file: "fonts/helvetica.ttf"
    id: helvetica_48
    size: 48
  - file: "fonts/helvetica.ttf"
    id: helvetica_24
    size: 24
  - file: "fonts/helvetica.ttf"
    id: helvetica_18
    size: 18
  - file: "fonts/helvetica.ttf"
    id: helvetica_header
    size: 15

  - file: "fonts/helvetica.ttf"
    id: helvetica_base
    size: 13
  - file: "fonts/Roboto-Regular.ttf"
    id: roboto
    size: 26
  - file: "fonts/Roboto-Regular.ttf"
    id: roboto_small
    size: 15

  - file: "gfonts://Roboto"
    id: roboto30
    size: 30

spi:
  type: octal
  clk_pin: 8
  data_pins:
    - 39
    - 40
    - 41
    - 42
    - ignore_strapping_warning: true
      number: 45
    - ignore_strapping_warning: true
      number: 46
    - 47
    - 48

display:
  - platform: mipi_spi
    model: t-display-s3
    rotation: 90
    lambda: |-
        int y = 8;
        int const y_inc = 26;
        it.printf(0, y, id(roboto),my_red, "Netz" ); it.printf(100, y, id(roboto), "%.1fW", id(netz).get_state()); y += y_inc;
        it.printf(0, y, id(roboto),my_blue, "PV 1");  it.printf(120, y, id(roboto), "%.1fW", id(pv1).get_state()); y += y_inc;
        it.printf(0, y, id(roboto),my_green, "PV 2+3+4");  it.printf(120, y, id(roboto), "%.1fW ", id(pv2).get_state()); y += y_inc;
        it.printf(0, y, id(roboto),my_yellow, "Eigen"); it.printf(100, y, id(roboto), "%.1fW", id(eigen).get_state()); y += y_inc;
        if (id(ip_address).has_state()) {
          it.print(it.get_width(), it.get_height(), id(roboto_small), TextAlign::BOTTOM_RIGHT, id(ip_address).state.c_str());
        }
        else{
          it.print(it.get_width(), it.get_height(), id(roboto_small), TextAlign::BOTTOM_RIGHT, "Not connected");
        }
        

