esphome:
  name: esp32-regenmengensensor
  friendly_name: esp32-regenmengensensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Nu8G+jVZU/hBv9IcWwg7bE5MNf+3EoioeV4AxGklrUE="

ota:
  - platform: esphome
    password: "528af3d2b037453d0a1839ae656fa71c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Regenmengensensor"
    password: "JlOeOiOBF0Fc"

captive_portal:

web_server:
  port: 80

sensor:
  - platform: esp32_hall
    name: "ESP32 Hall Sensor"
    update_interval: 1s