esphome:
  name: espnfc1
#  platform: ESP8266
#  board: esp07 #esp01_1m #esp07



esp32:
  board: esp32dev
  framework:
    type: arduino
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: high
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #use_address: 192.168.18.38 # for update

  ap:
    ssid: "Esp Nfc 2"
    password: "iEEjp6jc4KLw"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  password: "G24mqttATopenhab"

ota:
  platform: esphome
  password: "L2ATopenhab!"

web_server:
  port: 80

mqtt:
  # broker: 192.168.18.110
  # username: openhabian
  # password: "L2ATopenhab!"

  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"


i2c:
  #sda: 4
  #scl: 5
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a


pn532_i2c:
  update_interval: 1s
  on_tag:
    then:
      #    - mqtt.publish:
      #       topic: pn532/tag
      #       payload: !lambda 'return x;'
      - lambda: |-
          id(rfid_tag).publish_state(x);
          if (!tag.has_ndef_message()) {
             id(rfid_ndef).publish_state( x);
          }
          else{
            auto message = tag.get_ndef_message();
            auto records = message->get_records();
            for (auto &record : records) {
              std::string payload = record->get_payload();
                id(rfid_ndef).publish_state(payload);
            }
          }
          
  on_tag_removed:
    then:
     - lambda: |-
          id(rfid_tag).publish_state ("NoCard");
          id(rfid_ndef).publish_state("");
          
      #    - mqtt.publish:
      #       topic: pn532/tag_removed
      #        payload: !lambda 'return x;'
      # - text_sensor.template.publish:
      #   id: rfid_tag
      #   state: "NoCard"
      # - text_sensor.template.publish:
      #   id: rfid_ndef
      #   state: ""
 
 
          
text_sensor:
  - platform: template
    name: "RFID Tag"
    id: rfid_tag
  - platform: template
    name: "RFID Tag NDEF"
    id: rfid_ndef
    
    
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO16
    num_leds: 24 #37 #16
    name: "NeoPixel Light"
    id: my_light
    effects:
      - strobe:
      - strobe:
          name: Strobe Effect With Custom Values
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
      - lambda:
          name: My Custom Effect
          update_interval: 1s
          lambda: |-
            static int state = 0;
            auto call = id(my_light).turn_on();
            // Transition of 1000ms = 1s
            call.set_transition_length(1000);
            if (state == 0) {
              call.set_rgb(1.0, 1.0, 1.0);
            } else if (state == 1) {
              call.set_rgb(1.0, 0.0, 1.0);
            } else if (state == 2) {
              call.set_rgb(0.0, 0.0, 1.0);
            } else {
              call.set_rgb(1.0, 0.0, 0.0);
            }
            call.perform();
            state += 1;
            if (state == 4)
              state = 0;
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
      - addressable_scan:
    
      - addressable_twinkle:
      - addressable_twinkle:
          name: Twinkle Effect With Custom Values
          twinkle_probability: 1%
          progress_interval: 4ms