esphome:
  name: esp_bme680_7


esp8266:
  board: esp01
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: high
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp Bme680 7 Fallback Hotspot"
    password: "iEEjp6jc4KLw"

captive_portal:

# Enable logging
logger:
  level: DEBUG
# Enable Home Assistant API
#api:
#  password: "G24mqttATopenhab"

ota:
  platform: esphome
  password: "G24mqttATopenhab"

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: BME/status
    payload: online
  will_message:
    topic: BME/status
    payload: offline


i2c:
  sda: 0
  scl: 2
  scan: True
  #id: bus_a

bme680_bsec:
    # i2c address override (default is 0x76)
    address: 0x77

    # Temperature offset if device is in enclosure and reads too high (default is 0)
    #temperature_offset: 0.9

    # Mode for IAQ sensors if device is mobile (default is static)
    #iaq_mode: mobile

    # Interval at which to save BSEC state (default is 6 hours)
    state_save_interval: 4h

sensor:
  - platform: bme680_bsec
    temperature:
      # Temperature in °C
      name: "BME680 Temperature"
      filters:
        #- median
    pressure:
      # Pressure in hPa
      name: "BME680 Pressure"
      filters:
       # - median
    humidity:
      # Relative humidity %
      name: "BME680 Humidity"
      filters:
      #  - median
    gas_resistance:
      # Gas resistance in Ω
      name: "BME680 Gas Resistance"
      filters:
     #   - median
    iaq:
      # Indoor air quality value
      name: "BME680 IAQ"
      filters:
         - delta: 1.0
      #  - median
    iaq_accuracy:
      # IAQ accuracy as a numeric value of 0, 1, 2, 3
      name: "BME680 Numeric IAQ Accuracy"
    co2_equivalent:
      # CO2 equivalent estimate in ppm
      name: "BME680 CO2 Equivalent"
      filters:
        - delta: 1.0
       # - median
    breath_voc_equivalent:
      # Volatile organic compounds equivalent estimate in ppm
      name: "BME680 Breath VOC Equivalent"
      filters:
       #- median
       - delta: 0.1

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "BME680 IAQ Accuracy"
