esphome:
  name: esp_bme680_5

esp8266:
  board: esp01_1m


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: high
#  use_address: 192.168.40.216


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Bme680 2 Fallback Hotspot"
    password: "gRYvBmC4Bmog"

captive_portal:

#external_components:
#  - source: github://sermayoral/esphome@pm1006
#    components: [ pm1006 ]
    

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  password: "G24mqttATopenhab"

ota:
  platform: esphome
  password: "G24mqttATopenhab"

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: BME/status
    payload: online
  will_message:
    topic: BME/status
    payload: offline


i2c:
  sda: 0
  scl: 2
  scan: True
  #id: bus_a

bme680_bsec:
    # i2c address override (default is 0x76)
    address: 0x77

    # Temperature offset if device is in enclosure and reads too high (default is 0)
    #temperature_offset: 0.9

    # Mode for IAQ sensors if device is mobile (default is static)
    #iaq_mode: mobile

    # Interval at which to save BSEC state (default is 6 hours)
    state_save_interval: 4h

sensor:
  - platform: bme680_bsec
    temperature:
      name: "BME680 Temperature"
      id: temperature
      filters:
       - delta: 0.2
       - throttle: 30s
    pressure:
      name: "BME680 Pressure"
      
      filters:
       - delta: 0.2
       - throttle: 30s
    humidity:
      name: "BME680 Humidity"
      id: humidity
      filters:
       - delta: 0.2
       - throttle: 30s

    gas_resistance:
      name: "BME680 Gas Resistance"
      filters:
       - delta: 500.0
       - throttle: 30s
    iaq:
      name: "BME680 IAQ"
      id: iaq
      filters:
        - delta: 1.0
        - throttle: 30s
#        - median

    co2_equivalent:
      name: "BME680 CO2 Equivalent"
      id: co2_equivalent
      filters:
       - delta: 1.0
       - throttle: 30s

    breath_voc_equivalent:
      name: "BME680 Breath VOC Equivalent"
      id: breath_voc_equivalent
      filters:
       - delta: 0.1
       - throttle: 30s

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "BME680 IAQ Accuracy"

button:
  - platform: restart
    name: "Restart"