substitutions:
  device_name: Test status screen
  device_id: test-screen
  # Home assistant sensors
  # Weather conditions
  weather_conditions: weather.my_home
  # Outdoor sensors
  outdoor_temperature: sensor.outdoor_temperature
  outdoor_humidity: sensor.outdoor_humidity
  outdoor_rainfall: sensor.outdoor_rainfall
  outdoor_wind_strength: sensor.outdoor_wind_strength
  # Indoor sensors
  indoor_temperature: sensor.indoor_temperature
  indoor_humidity: sensor.indoor_humidity
  indoor_pressure: sensor.indoor_pressure
  indoor_co2: sensor.indoor_co2
  # Alarms
  # Any counter, will be shown as number 0..9
  lights_counter: sensor.lights_counter
  # Alarmo status
  alarmo_status: alarm_control_panel.alarmo
  # Radiation alarm
  radiation_alarm: binary_sensor.radiation_alarm

web_server:


esphome:
  name: ${device_id}
  name_add_mac_suffix: true
  on_boot:
    - priority: 220.0
      then:
        - it8951e.clear
        - delay: 100ms
        - component.update: m5paper_display
    - priority: -100.0
      then:
        - delay: 10s
        - component.update: m5paper_display

esp32:
  board: esp32dev

  framework:
    type: arduino

external_components:
  - source: github://Passific/m5paper_esphome

# Enable logging
logger:
  level: DEBUG

# Enable psram
psram:

# Enable Home Assistant API
api:

ota:


font:
  - file: "gfonts://Source Sans Pro"
    id: font_main
    size: 40


  # https://pictogrammers.github.io/@mdi/font/5.3.45/
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_icons
    size: 160
    glyphs:
      - "\U000F0594" # clear-night
      - "\U000F0590" # cloudy
      - "\U000F0595" # partlycloudy
      - "\U000F0591" # fog      
      - "\U000F0592" # hail
      - "\U000F0593" # lightning
      - "\U000F067E" # lightning-rainy
      - "\U000F0596" # pouring
      - "\U000F0597" # rainy
      - "\U000F0F36" # snowy
      - "\U000F067F" # snowy-rainy
      - "\U000F0599" # sunny
      - "\U000F059D" # windy
      - "\U000F059E" # windy-variant
      - "\U000F0F38" # exceptional


display:
  - platform: it8951e
    id: m5paper_display
    model: M5EPD
    cs_pin: GPIO15
    reset_pin: GPIO23
    reset_duration: 100ms
    busy_pin: GPIO27
    rotation: 0
    reversed: False
    update_interval: never
    lambda: |-
       ESP_LOGI("display_lambda", "Lambda is running!");
      
        // Border
        //it.rectangle(1, 1, 960-2, 540-2, Color::BLACK);

        //it.filled_rectangle(1, 1, 100, 540, Color::WHITE);
        
        //it.filled_rectangle(100, 1, 200, 540, Color::BLACK);
        //it.filled_rectangle(300, 1, 400, 540);

        //it.filled_rectangle(500, 1, 700, 540, Color::BLACK);

        // Text
        it.print(180, 50, id(font_main), Color::BLACK, "Hello World!");
        it.print(180, 100, id(font_main), Color::WHITE, "LilyGo T5-4.7");
        
        it.print(180, 150, id(font_main), "Test Default Color");

        // Icons
        it.printf(180, 300, id(font_icons), Color::BLACK, "\U000F0595"); // mdi-weather-cloudy
        it.printf(300, 300, id(font_icons), Color::WHITE, "\U000F0593"); // mdi-weather-cloudy

   

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

