# ESPHome-Konfiguration for Toshiba/Carrier HVAC

esphome:
  name: toshiba-hvac-controller

esp32:
  board: esp32dev
  framework:
    type: esp-idf


# Enable logging
logger:
  level: VERY_VERBOSE
  logs:
    component: INFO
    mqtt: INFO
    api: INFO
    web_server: INFO
    wifi: INFO
    esp32.preferences: INFO
    scheduler: INFO
    # Keep our component and UART verbose
    toshiba_hvac: VERY_VERBOSE
    uart: VERY_VERBOSE

ota:
  - platform: esphome  
    password: !secret ota_password

api:
  encryption:
    key: !secret api_encryption_key

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.18.204 # for update
  #output_power: 12dB


# Define the pins connected to the Toshiba/Carrier HVAC interface
uart:
  id: hvac_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600  # Standard baud rate for Toshiba, adjust if needed
  parity: EVEN

# External Component for Toshiba HVAC

external_components:
  #- source: github://martin-at-schorsch/esphome-toshiba-hvac 
  - source:
      type: local
      path: components
    components: [toshiba_hvac]


# climate Component
climate:
  - platform: toshiba_hvac # Use the platform of the external component
    name: "Toshiba HVAC"
    uart_id: hvac_uart # Reference to the UART configuration
    outdoor_temperature:
      name: "Toshiba Outdoor Temperature"
    power_select:
      name: "Toshiba Power Select" # Select 100%, 75%, 50%
    pure_switch:
      name: "Toshiba Pure Switch" # Ionizer control
    query_button:
      name: "Toshiba Force Update" # Manual state refresh

# Force inclusion of sensor component
# Force inclusion of core components
sensor:
switch:
select:
button: