# ESPHome-Konfiguration for Toshiba/Carrier HVAC

esphome:
  name: toshiba-hvac-controller

esp32:
  board: esp32dev
  framework:
    type: arduino


# Enable logging
logger:

ota:
  - platform: esphome  
    password: !secret ota_password

api:
  encryption:
    key: !secret api_encryption_key

#mqtt:
#  broker: !secret mqtt_host
#  username: !secret mqtt_username
#  password: !secret mqtt_password

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


# Define the pins connected to the Toshiba/Carrier HVAC interface
uart:
  id: hvac_uart
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 9600  # Standard baud rate for Toshiba, adjust if needed
  stop_bits: 1
  parity: NONE
  #parity: EVEN

# External Component for Toshiba HVAC

external_components:
  - source: github://martin-at-schorsch/esphome-toshiba-hvac 
  #- source:
  #    type: local
  #    path: components
    components: [toshiba_hvac]


# climate Component
climate:
  - platform: toshiba_hvac # Use the platform of the external component
    name: "Toshiba HVAC"
    uart_id: hvac_uart # Reference to the UART configuration
    