# ESPHome-Konfiguration f체r Toshiba/Carrier HVAC

esphome:
  name: toshiba-hvac-pedobry

esp32:
  board: esp32dev
  framework:
    type: arduino


# Enable logging
logger:

api:
#  encryption:
#    key: "6gOKpWUn++4mS9jkMZwuJj+LZzcOJDZz6+4Iqg5o3I4="

ota:
  - platform: esphome
    password: "8a0cc881c4038abeb32bc5f0b8ca77c3"


web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test1 Fallback Hotspot"
    password: "eQK2U8OFwGtk"

# Define the pins connected to the Toshiba/Carrier HVAC interface
uart:
  id: hvac_uart
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 9600  # Standard-Baudrate f체r Toshiba, ggf. anpassen
  parity: EVEN

# External Component f체r Toshiba HVAC

external_components:
  - source: 
      type: git
      url: https://github.com/pedobry/esphome_toshiba_suzumi
    components: [toshiba_suzumi]


climate:
  - platform: toshiba_suzumi
    name: living-room
    id: living_room
    uart_id: hvac_uart
    outdoor_temp:        # Optional. Outdoor temperature sensor
      name: Outdoor Temp
      filters:
        # Filter out value 127 as that's what unit sends when it can's measure the outside temp.
        - filter_out: 127 
    power_select:
      name: "Power level"
    #horizontal_swing: true # Optional. Uncomment if your HVAC supports also horizontal swing
    #supported_presets:          # Optional. Enable only the features your HVAC
      #- "Standard"
      #- "Hi POWER"
      #- "ECO"
      #- "Fireplace 1"
      #- "Fireplace 2"
      #- "8 degrees"             # When enabling this mode, the temp range is set to 5-30째C
      #- "Silent#1"
      #- "Silent#2"
      #- "Sleep"
      #- "Floor"
      #- "Comfort"
    #disable_wifi_led: true # Optional. Disable Wifi LED on internal unit.

button:
  - platform: template
    name: "Scan for unknown sensors"
    icon: "mdi:reload"
    on_press:
      then:
        - lambda: |-
            auto* controller = static_cast<toshiba_suzumi::ToshibaClimateUart*>(id(living_room));
            controller->scan();    