esphome:
  name: esp32_bme680_2


esp32:
  board: featheresp32
  framework:
    type: arduino
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: high


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Bme680 2 Fallback Hotspot"
    password: "gRYvBmC4Bmog"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  password: "G24mqttATopenhab"

ota:
  platform: esphome
  password: "G24mqttATopenhab"

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: BME/status
    payload: online
  will_message:
    topic: BME/status
    payload: offline


i2c:
  sda: 21
  scl: 22
  scan: True
  #id: bus_a

bme680_bsec:
    # i2c address override (default is 0x76)
    address: 0x77

    # Temperature offset if device is in enclosure and reads too high (default is 0)
    #temperature_offset: 0.9

    # Mode for IAQ sensors if device is mobile (default is static)
    #iaq_mode: mobile

    # Interval at which to save BSEC state (default is 6 hours)
    state_save_interval: 4h

sensor:
  - platform: bme680_bsec
    temperature:
      name: "BME680 Temperature"
      filters:
       - delta: 0.2
    pressure:
      name: "BME680 Pressure"
      filters:
       - delta: 0.2

    humidity:
      name: "BME680 Humidity"
      filters:
       - delta: 0.2

    gas_resistance:
      name: "BME680 Gas Resistance"
      filters:
       - delta: 500.0

    iaq:
      name: "BME680 IAQ"
      filters:
        - delta: 1.0
#        - median

    co2_equivalent:
      name: "BME680 CO2 Equivalent"
      filters:
       - delta: 1.0

    breath_voc_equivalent:
      name: "BME680 Breath VOC Equivalent"
      filters:
       - delta: 0.1

  - platform: adc
    pin: 34
    attenuation: 6db 
    name: "VBatt"
    id: vcc
    update_interval: 60s
    filters:
      - multiply: 1.76

  - platform: template
    name: batterylevel
    id: batterylevel
    unit_of_measurement: '%'
    update_interval: 60s
    lambda: |-
      return ((id(vcc).state -3.2) * 110);     
 # I know infering the battery from voltage only is misleading, but I'll take it. Considering linear decay (again, i'll take it), max=2.23, min=1.38
     

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO35
      inverted: true
    id: tdisplay_button_input_1
    name: "Input 1"
#    on_click:
#      then:
#        - homeassistant.service:
#            service: switch.toggle
#            data:
#              entity_id: switch.tasmota

  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    id: tdisplay_button_input_0
    name: "Input 0"
#    on_click:
#      then:
#        - homeassistant.service:
#            service: switch.toggle
#            data:
#              entity_id: switch.termo

  - platform: status
    name: "Node Status"
    id: system_status              

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "BME680 IAQ Accuracy"


