# LilyGO T5_V2.3_2.13


esphome:
  name: esp32-t5


# Enable logging

esp32:
  board: esp32dev
  framework:
    type: arduino
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: high
  use_address: 192.168.40.218


captive_portal:



# Home Assistant
api:

ota:
  platform: esphome
  password: "G24mqttATopenhab"

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password


binary_sensor:
  - platform: gpio
    pin:
        number: 39
        inverted: true
    name: "button"
    filters:
    - delayed_off: 10ms



sensor:
  - platform: mqtt_subscribe
    name: "Data from topic"
    id: lr_temp
    topic: esp_bme680_1/sensor/bme680_temperature/state  
    on_value:
        then:
          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: termostat_temp
    topic: esp_bme680_2/sensor/bme680_temperature/state
    on_value:
        then:
          - component.update: epaper
    
  - platform: mqtt_subscribe
    name: "Data from topic"
    id: lrh_temp
    topic: esp_bme680_3/sensor/bme680_temperature/state 
    on_value:
        then:
          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: toilet_temp
    topic: esp_bme680_4/sensor/bme680_temperature/state   
    on_value:
        then:
          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: sr_temp
    topic: esp_bme680_5/sensor/bme680_temperature/state
    on_value:
        then:
          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: srh_temp
    topic: esp_bme680_6/sensor/bme680_temperature/state 
    on_value:
        then:
          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: outdoor_temp
    topic: esp_bme680_7/sensor/bme680_temperature/state 
    on_value:
        then:
          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: lr_humi
    topic: esp_bme680_1/sensor/bme680_humidity/state
    on_value:
        then:
          - component.update: epaper
    
  - platform: mqtt_subscribe
    name: "Data from topic"
    id: termostat_humi
    topic: esp_bme680_2/sensor/bme680_humidity/state
    on_value:
        then:
          - component.update: epaper
    
  - platform: mqtt_subscribe
    name: "Data from topic"
    id: srh_humi
    topic: esp_bme680_3/sensor/bme680_humidity/state
    on_value:
        then:
          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: outdoor_humi
    topic: esp_bme680_4/sensor/bme680_humidity/state
    on_value:
        then:
          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: sr_humi
    topic: esp_bme680_5/sensor/bme680_humidity/state 
    on_value:
        then:
          - component.update: epaper
          
  - platform: mqtt_subscribe
    name: "Data from topic"
    id: lrh_humi
    topic: esp_bme680_6/sensor/bme680_humidity/state
    on_value:
        then:
          - component.update: epaper
          
  - platform: mqtt_subscribe
    name: "esp_bme680_1_temperature"
    id: toilet_humi
    topic: esp_bme680_7/sensor/bme680_humidity/state
    on_value:
        then:
          - component.update: epaper





spi:
    clk_pin: 18
    mosi_pin: 23

font:
  - file: "fonts/Helvetica.ttf"
    id: arial
    size: 16
  - file: "fonts/Helvetica.ttf"
    id: helvetica_48
    size: 48
  - file: "fonts/Helvetica.ttf"
    id: helvetica_24
    size: 24
  - file: "fonts/Helvetica.ttf"
    id: helvetica_18
    size: 18
  - file: "fonts/Helvetica.ttf"
    id: helvetica_header
    size: 15

  - file: "fonts/Helvetica.ttf"
    id: helvetica_base
    size: 13

display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4
    reset_pin: 16
    model: 2.13in-ttgo-b73
    rotation: 90
    full_update_every: 100
    update_interval: never
    lambda: |-
        int y = 8;
        int const y_inc = 16;
        it.printf(0, y, id(arial), "Wohnzimmer %.1f°C %.1f%%", id(lr_temp).get_state(), id(lr_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Thermostat %.1f°C %.1f%%", id(termostat_temp).get_state(), id(termostat_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Heizkoerper %.1f°C %.1f%%", id(lrh_temp).get_state(), id(lrh_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Klo %.1f°C %.1f%%", id(toilet_temp).get_state(), id(toilet_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Schlafzimmer %.1f°C %.1f%%", id(sr_temp).get_state(), id(sr_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Heizkoerper %.1f°C %.1f%%", id(srh_temp).get_state(), id(srh_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Aussen %.1f°C %.1f%%", id(outdoor_temp).get_state(), id(outdoor_humi).get_state()); y += y_inc;

