# LilyGO T5_V2.3_2.13


esphome:
  name: esp32-t5-sepp


# Enable logging

esp32:
  board: esp32dev
  framework:
    type: arduino
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: high
  use_address: 192.168.40.218


captive_portal:



# Home Assistant
api:

ota:
  platform: esphome
  password: "G24mqttATopenhab"

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password


binary_sensor:
  - platform: gpio
    pin:
        number: 39
        inverted: true
    name: "button"
    filters:
    - delayed_off: 10ms
    on_state:
        then:
          - component.update: epaper


sensor:
  - platform: mqtt_subscribe
    name: "Netz"
    id: netz
    topic: esp_bme680_7/sensor/bme680_humidity/state 
    on_value:
        then:
 #         - component.update: epaper

  - platform: mqtt_subscribe
    name: "PV1"
    id: pv1
    topic: esp_bme680_5/sensor/bme680_temperature/state
    on_value:
        then:
 #         - component.update: epaper
    
  - platform: mqtt_subscribe
    name: "PV2"
    id: pv2
    topic: esp_bme680_6/sensor/bme680_temperature/state 
    on_value:
        then:
 #         - component.update: epaper

  - platform: mqtt_subscribe
    name: "Eigen"
    id: eigen
    topic: esp_bme680_7/sensor/bme680_temperature/state   
    on_value:
        then:
          - component.update: epaper





spi:
    clk_pin: 18
    mosi_pin: 23

font:
  - file: "fonts/Roboto.ttf"
    id: roboto
    size: 28
  - file: "fonts/Helvetica.ttf"
    id: helvetica_48
    size: 48
  - file: "fonts/Helvetica.ttf"
    id: helvetica_24
    size: 24
  - file: "fonts/Helvetica.ttf"
    id: helvetica_18
    size: 18
  - file: "fonts/Helvetica.ttf"
    id: helvetica_header
    size: 15

  - file: "fonts/Helvetica.ttf"
    id: helvetica_base
    size: 13

display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4
    reset_pin: 16
    model: 2.13in-ttgo-b73
    #model: 2.13in-ttgo
    #model: 2.13in-ttgo-b1
    
    rotation: 90
    full_update_every: 500
    update_interval: never
    lambda: |-
        int y = 8;
        int const y_inc = 29;
        it.printf(0, y, id(roboto), "Netz" ); it.printf(90, y, id(roboto), "%.1fW", id(netz).get_state()); y += y_inc;
        it.printf(0, y, id(roboto), "PV 1");  it.printf(90, y, id(roboto), "%.1fW", id(pv1).get_state()); y += y_inc;
        it.printf(0, y, id(roboto), "PV 2");  it.printf(90, y, id(roboto), "%.1fW ", id(pv2).get_state()); y += y_inc;
        it.printf(0, y, id(roboto), "Eigen"); it.printf(90, y, id(roboto), "%.1fW", id(eigen).get_state()); y += y_inc;
        
