esphome:
  name: esp32-t5-75
  friendly_name: esp32-t5-7.5

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  encryption:
#    key: "K2mnpdSeYYPZXWC645EwH92vDgtXS2kskRozyrjVCXM="
# Use API only if there is a client connecting, otherwise every 15 minutes a reboot is triggered


ota:
  - platform: esphome
    password: "067f761c9fdc73a753be44f5bd3a1c48"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  use_address: 192.168.30.101 #192.168.40.218


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-T5-75 Fallback Hotspot"
    password: "Uks7E1VV0TdL"

captive_portal:





web_server:
  port: 80

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  
  on_connect:
    then:
      - component.update: epaper


binary_sensor:
  - platform: gpio
    pin:
        number: 39
        inverted: true
    name: "button"
    filters:
    - delayed_off: 10ms



sensor:
  - platform: mqtt_subscribe
    name: "Data from topic"
    id: lr_temp
    topic: esp_bme680_1/sensor/bme680_temperature/state  
    filters:
    - throttle: 60s
    on_value:
        then:
#          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: termostat_temp
    topic: esp_bme680_2/sensor/bme680_temperature/state
    filters:
    - throttle: 60s
    on_value:
        then:
  #        - component.update: epaper
    
  - platform: mqtt_subscribe
    name: "Data from topic"
    id: lrh_temp
    topic: esp_bme680_3/sensor/bme680_temperature/state 
    filters:
    - throttle: 60s
    on_value:
        then:
#          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: toilet_temp
    topic: esp_bme680_4/sensor/bme680_temperature/state   
    filters:
    - throttle: 60s
    on_value:
        then:
#          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: sr_temp
    topic: esp_bme680_5/sensor/bme680_temperature/state
    filters:
    - throttle: 60s

    on_value:
        then:
#          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: srh_temp
    topic: esp_bme680_6/sensor/bme680_temperature/state 
    filters:
    - throttle: 60s
    on_value:
        then:
#          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: outdoor_temp
    topic: esp_bme680_7/sensor/bme680_temperature/state 
    filters:
    - throttle: 60s

    on_value:
        then:
#          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: lr_humi
    topic: esp_bme680_1/sensor/bme680_humidity/state
    filters:
    - throttle: 60s
    
    on_value:
        then:
#          - component.update: epaper
    
  - platform: mqtt_subscribe
    name: "Data from topic"
    id: termostat_humi
    topic: esp_bme680_2/sensor/bme680_humidity/state
    filters:
    - throttle: 60s

    on_value:
        then:
#          - component.update: epaper
    
  - platform: mqtt_subscribe
    name: "Data from topic"
    id: srh_humi
    topic: esp_bme680_3/sensor/bme680_humidity/state
    filters:
    - throttle: 60s

    on_value:
        then:
#         - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: outdoor_humi
    topic: esp_bme680_4/sensor/bme680_humidity/state
    filters:
    - throttle: 60s

    on_value:
        then:
#          - component.update: epaper

  - platform: mqtt_subscribe
    name: "Data from topic"
    id: sr_humi
    topic: esp_bme680_5/sensor/bme680_humidity/state 
    filters:
    - throttle: 60s


    on_value:
        then:
#          - component.update: epaper
          
  - platform: mqtt_subscribe
    name: "Data from topic"
    id: lrh_humi
    topic: esp_bme680_6/sensor/bme680_humidity/state
    filters:
    - throttle: 60s

    on_value:
        then:
#          - component.update: epaper
          
  - platform: mqtt_subscribe
    name: "esp_bme680_1_temperature"
    id: toilet_humi
    topic: esp_bme680_7/sensor/bme680_humidity/state
    filters:
    - throttle: 60s

    
    on_value:
        then:
#          - component.update: epaper





spi:
    clk_pin: 18
    mosi_pin: 23

font:
  - file: "fonts/Helvetica.ttf"
    id: arial
    size: 16
  - file: "fonts/Helvetica.ttf"
    id: helvetica_48
    size: 48
  - file: "fonts/Helvetica.ttf"
    id: helvetica_24
    size: 24
  - file: "fonts/Helvetica.ttf"
    id: helvetica_18
    size: 18
  - file: "fonts/Helvetica.ttf"
    id: helvetica_header
    size: 15

  - file: "fonts/Helvetica.ttf"
    id: helvetica_base
    size: 13

display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4
    reset_pin: 16
    model: 7.50in-bV3-bwr
    rotation: 0
    #full_update_every: 100
    update_interval: 600s #never
    lambda: |-
        const auto BLACK   = Color(0,   0,   0,   0);
        const auto RED     = Color(255, 0,   0,   0);
        const auto GREEN   = Color(0,   255, 0,   0);
        const auto BLUE    = Color(0,   0,   255, 0);
        const auto YELLOW  = Color(255, 255, 0,   0);
        const auto ORANGE  = Color(255, 127, 0,   0);
        const auto WHITE   = Color(255, 255, 255, 0);
        int y = 8;
        int const y_inc = 16;
        it.printf(0, y, id(arial), RED, "Wohnzimmer %.1f°C %.1f%%", id(lr_temp).get_state(), id(lr_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Thermostat %.1f°C %.1f%%", id(termostat_temp).get_state(), id(termostat_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), RED, "Heizkoerper %.1f°C %.1f%%", id(lrh_temp).get_state(), id(lrh_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Klo %.1f°C %.1f%%", id(toilet_temp).get_state(), id(toilet_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Schlafzimmer %.1f°C %.1f%%", id(sr_temp).get_state(), id(sr_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Heizkoerper %.1f°C %.1f%%", id(srh_temp).get_state(), id(srh_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Aussen %.1f°C %.1f%%", id(outdoor_temp).get_state(), id(outdoor_humi).get_state()); y += y_inc;

