esphome:
  name: liligo-t5-47-epaper-plus
#  platformio_options:
#    board_dir: boards
#    #include https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/blob/master/platformio/boards/lilygo-t5-47-plus.json as custom board
#    board: lilygo-t5-47-plus

esp32:
  variant: esp32s3
#  board: lilygo-t5-47-plus

  framework:
    type: arduino
    # You don't need to specify version and platform_version

i2c:
  sda: GPIO17
  scl: GPIO18
  # There is some problems with i2c scan so turn scan off if problem appear on your board
  scan: false
  id: bus_a

external_components:
  - source: github://nickolay/esphome-lilygo-t547plus
    components: ["t547"]



  - source: github://landonr/lilygo-tdisplays3-esphome
    components: [tdisplays3]


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Ttgo-Display"
    password: "gRYvBmC4Bmog"

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password




binary_sensor:

  - platform: status
    name: "Node Status"
    id: system_status              


sensor:
  # Wert1
  - platform: mqtt_subscribe
    name: "Netz"
    id: netz
    topic: pv/sensor/netz/state 
    on_value:
        then:
 #         - component.update: epaper
  # Wert2
  - platform: mqtt_subscribe
    name: "PV1"
    id: pv1
    topic: pv/sensor/pv1/state
    on_value:
        then:
 #         - component.update: epaper
  # Wert3  
  - platform: mqtt_subscribe
    name: "PV2"
    id: pv2
    topic: pv/sensor/pv2/state 
    on_value:
        then:
 #         - component.update: epaper
  # Wert4
  - platform: mqtt_subscribe
    name: "Eigen"
    id: eigen
    topic: pv/sensor/eigenverbrauch/state   
    on_value:
        then:
          #- component.update: epaper
  # Akt IP Adr
# Example configuration entry
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      id: ip_address


button:
  - platform: restart
    name: "Restart"

switch:
  - platform: gpio
    pin: GPIO38
    name: "Backlight"
    id: backlight
    internal: true
    restore_mode: RESTORE_DEFAULT_ON

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_gray
    red: 50%
    green: 50%
    blue: 50%

font:
  - file: "fonts/helvetica.ttf"
    id: helvetica_48
    size: 48
  - file: "fonts/helvetica.ttf"
    id: helvetica_24
    size: 24
  - file: "fonts/helvetica.ttf"
    id: helvetica_18
    size: 18
  - file: "fonts/helvetica.ttf"
    id: helvetica_header
    size: 15

  - file: "fonts/helvetica.ttf"
    id: helvetica_base
    size: 13
  - file: "fonts/Roboto-Regular.ttf"
    id: roboto
    size: 26
  - file: "fonts/Roboto-Regular.ttf"
    id: roboto_small
    size: 15

  - file: "gfonts://Roboto"
    id: roboto30
    size: 30



display:
  - platform: t547
    rotation: 90
    lambda: |-
        int y = 8;
        int const y_inc = 26;
        it.printf(0, y, id(roboto),my_red, "Netz" ); it.printf(100, y, id(roboto), "%.1fW", id(netz).get_state()); y += y_inc;
        it.printf(0, y, id(roboto),my_blue, "PV 1");  it.printf(120, y, id(roboto), "%.1fW", id(pv1).get_state()); y += y_inc;
        it.printf(0, y, id(roboto),my_green, "PV 2+3");  it.printf(120, y, id(roboto), "%.1fW ", id(pv2).get_state()); y += y_inc;
        it.printf(0, y, id(roboto),my_yellow, "Eigen"); it.printf(100, y, id(roboto), "%.1fW", id(eigen).get_state()); y += y_inc;
        if (id(ip_address).has_state()) {
          it.print(it.get_width(), it.get_height(), id(roboto_small), TextAlign::BOTTOM_RIGHT, id(ip_address).state.c_str());
        }
        else{
          it.print(it.get_width(), it.get_height(), id(roboto_small), TextAlign::BOTTOM_RIGHT, "Not connected");
        }
        


