esphome:
  name: esp_meter_1


esp8266:
  board: esp01_1m
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: high
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  use_address: 192.168.18.38 # for update

  ap:
    ssid: "Esp Meter Fallback Hotspot"
    password: "iEEjp6jc4KLw"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  password: "G24mqttATopenhab"

ota:
  platform: esphome
  password: "L2ATopenhab!"

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password



sensor:
  - platform: pulse_counter
    pin: 
      number: GPIO12
      mode: INPUT_PULLUP
    unit_of_measurement: 'kW'
    name: 'Power Meter Main'
    internal_filter: 50us # phototransistor

#    count_mode: 
#      - falling_edge: increment

    filters:
      - multiply: 0.06
      #  factor of 0.06 from pulses/min to kW for 1000 pulse/kWh

  - platform: pulse_counter
    pin: 
      number: GPIO13
      mode: INPUT_PULLUP
    unit_of_measurement: 'kW'
    name: 'Power Meter Sub 1'
    internal_filter: 10us # 50ms  #S0

#    count_mode: 
#      - falling_edge: increment

    filters:
      - multiply: 0.06
      #  factor of 0.06 from pulses/min to kW for 1000 pulse/kWh

  - platform: pulse_counter
    pin: 
      number: GPIO14
      mode: INPUT_PULLUP

    unit_of_measurement: 'kW'
    name: 'Power Meter Sub 2'
    internal_filter: 10us # 50ms  #S0

#    count_mode: 
#      - falling_edge: increment

    filters:
      - multiply: 0.06
      #  factor of 0.06 from pulses/min to kW for 1000 pulse/kWh


  - platform: wifi_signal
    name: "WiFi Signal Sensor"
