# LilyGO T5_V2.3_2.13

esphome:
  name: lilygo


esp32:
  board: esp32dev
  framework:
    type: arduino
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "LilyGO fallback hotspot"
    password: !secret wifi_password


captive_portal:

logger:

# Home Assistant
api:

ota:
  platform: esphome
    password: !secret wifi_password

binary_sensor:
  - platform: gpio
    pin:
        number: 39
        inverted: true
    name: "button"
    filters:
    - delayed_off: 10ms

esp32_ble_tracker:

sensor:
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:B5:81:90" # ATC_B58190
    bindkey: "00000000000000000000000000000000"
    temperature:
        name: "lr_heater temperature"
        id: lrh_temp
    humidity:
        name: "lr_heater humidity"
        id: lrh_humi
        on_value:
            then:
              - component.update: epaper

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:4D:13:73"  # ATC_4D1373
    bindkey: "00000000000000000000000000000000"
    temperature:
        name: "toilet temperature"
        id: toilet_temp
    humidity:
        name: "toilet humidity"
        id: toilet_humi
        on_value:
            then:
              - component.update: epaper

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:A7:81:A4" # ATC_A781A4
    bindkey: "00000000000000000000000000000000"
    temperature:
        name: "living_room temperature"
        id: lr_temp
    humidity:
        name: "living_room humidity"
        id: lr_humi
        on_value:
            then:
              - component.update: epaper

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:BE:35:D2" # ATC_BE35D2
    bindkey: "00000000000000000000000000000000"
    temperature:
        name: "kitchen temperature"
        id: kitchen_temp
    humidity:
        name: "kitchen humidity"
        id: kitchen_humi
        on_value:
            then:
              - component.update: epaper

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:0C:BE:2C" # ATC_0CBE2C
    bindkey: "00000000000000000000000000000000"
    temperature:
        name: "sr_heater temperature"
        id: srh_temp
    humidity:
        name: "sr_heater humidity"
        id: srh_humi
        on_value:
            then:
              - component.update: epaper

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:39:A9:42" # ATC_39A942
    bindkey: "00000000000000000000000000000000"
    temperature:
        name: "outdoor temperature"
        id: outdoor_temp
    humidity:
        name: "outdoor humidity"
        id: outdoor_humi
        on_value:
            then:
              - component.update: epaper

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:C5:27:15" # ATC_C52715
    bindkey: "00000000000000000000000000000000"
    temperature:
        name: "termostat temperature"
        id: termostat_temp
    humidity:
        name: "termostat humidity"
        id: termostat_humi
        on_value:
            then:
              - component.update: epaper

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:09:6A:3A" # ATC_096A3A
    bindkey: "00000000000000000000000000000000"
    temperature:
        name: "sleeping_room temperature"
        id: sr_temp
    humidity:
        name: "sleeping_room humidity"
        id: sr_humi
        on_value:
            then:
              - component.update: epaper

spi:
    clk_pin: 18
    mosi_pin: 23

font:
  - file: "/usr/share/fonts/truetype/msttcorefonts/Arial.ttf"
    id: arial
    size: 16

display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4
    reset_pin: 16
    model: 2.13in-ttgo-b73
    rotation: 90
    full_update_every: 100
    update_interval: never
    lambda: |-
        int y = 8;
        int const y_inc = 16;
        it.printf(0, y, id(arial), "Wohnzimmer %.1f°C %.1f%%", id(lr_temp).get_state(), id(lr_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Thermostat %.1f°C %.1f%%", id(termostat_temp).get_state(), id(termostat_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Heizkoerper %.1f°C %.1f%%", id(lrh_temp).get_state(), id(lrh_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Klo %.1f°C %.1f%%", id(toilet_temp).get_state(), id(toilet_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Schlafzimmer %.1f°C %.1f%%", id(sr_temp).get_state(), id(sr_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Heizkoerper %.1f°C %.1f%%", id(srh_temp).get_state(), id(srh_humi).get_state()); y += y_inc;
        it.printf(0, y, id(arial), "Aussen %.1f°C %.1f%%", id(outdoor_temp).get_state(), id(outdoor_humi).get_state()); y += y_inc;

