esphome:
  name: lilygo-t5-47-move-test
  
esp32:
  board: esp32dev
  framework:
    type: arduino

psram:
  mode: quad
  speed: 40MHz


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome  
    password: !secret ota_password

api:
  encryption:
    key: !secret api_encryption_key

external_components:
  - source:
      type: local
      path: components
    components: [lilygo_t5_47_display]

logger:
  level: DEBUG

font:
  - file: "gfonts://Source Sans Pro"
    id: font_main
    size: 40

display:
  - platform: lilygo_t5_47_display
    id: t5_display
    full_update_every: 5
    power_off_delay_enabled: false
    update_interval: 2s # Update every 2 seconds
    lambda: |-
      static int y_pos = 0;
      static int direction = 1;
      
      // Calculate new position
      y_pos += (20 * direction);
      if (y_pos > 400) {
        y_pos = 400;
        direction = -1;
      } else if (y_pos < 0) {
        y_pos = 0;
        direction = 1;
      }
      
      // Clear Screen Logic is handled by component (partial update)
      // But we drawing backgrounds helps visualize overwrites
      
      // Draw Left Side (White Background)
      it.filled_rectangle(0, 0, 480, 540, Color::WHITE);
      
      // Draw Right Side (Black Background)
      it.filled_rectangle(480, 0, 480, 540, Color::BLACK);
      
      // Draw Text Left (Black on White)
      // Moving Text
      it.print(20, 50 + y_pos, id(font_main), Color::BLACK, "Moving Text (B/W)");
      
      // Draw Text Right (White on Black)
      it.print(500, 50 + y_pos, id(font_main), Color::WHITE, "Moving Text (W/B)");
      
      // Static Text for reference
      it.print(20, 20, id(font_main), Color::BLACK, "Static Header");
      it.print(500, 20, id(font_main), Color::WHITE, "Static Header");

      ESP_LOGI("display_lambda", "Drawn at Y=%d", 50 + y_pos);
